"""add apollo_id and retry_count

Revision ID: 33c323a725a1
Revises: add_email_metadata
Create Date: 2026-06-17 12:04:40.155725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33c323a725a1'
down_revision: Union[str, Sequence[str], None] = 'add_email_metadata'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('leads', sa.Column('apollo_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_leads_apollo_id'), 'leads', ['apollo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_apollo_id'), table_name='leads')
    op.drop_column('leads', 'apollo_id')
    op.drop_column('emails', 'retry_count')
    # ### end Alembic commands ###
