"""Add extra lead fields

Revision ID: d50c47228c21
Revises: 41904db62b76
Create Date: 2026-06-15 16:26:01.777419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd50c47228c21'
down_revision: Union[str, Sequence[str], None] = '41904db62b76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('city', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('state', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('country', sa.String(), nullable=True))
    op.add_column('leads', sa.Column('industry', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'industry')
    op.drop_column('leads', 'country')
    op.drop_column('leads', 'state')
    op.drop_column('leads', 'city')
    op.drop_column('leads', 'phone_number')
    # ### end Alembic commands ###
